### PR TITLE
Fix CDI 1.3 importer pod deletion logic change 

### PR DESCRIPTION
**Pull request by shiywang**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubevirt/kubevirt-ansible/issues/428

**Special notes for your reviewer**:

**Release note**:

```release-note
bump CDI version to 1.3.0
```

### CODE REVIEW

**Comment by gbenhaim** [comment]
@shiywang Can you please rebase?

**Comment by shiywang** [comment]
@gbenhaim done, PTAL

**Comment by shiywang** [comment]
Test Result (5 failures / +3)

Tests Suite.RBAC RBAC with default permission should allow to access subresource endpoint.

Tests Suite.RBAC RBAC Authorization with admin permission should allow to access subresource endpoint

Tests Suite.RBAC RBAC Authorization with edit permission should allow to access subresource endpoint


Tests Suite.RBAC RBAC Authorization with view permission should not allow to access subresource endpoint


Tests Suite.VIRT RNG test With VirtIO RNG device Virtio rng device should be present


@ILpinto @adityaramteke could you please take a look at the failures since CDI update ?

**Comment by ILpinto** [comment]
@shiywang 
Looks like environment issue which started at: RBAC test 
11:15:38 [check-patch.openshift_3-10.el7.x86_64]     Should schedule the VM "vm-cirros" in kubevirt-test-default namespace to start
11:15:38 [check-patch.openshift_3-10.el7.x86_64]     Expected error:
11:15:38 [check-patch.openshift_3-10.el7.x86_64]         <*errors.errorString | 0xc420500cf0>: {
11:15:38 [check-patch.openshift_3-10.el7.x86_64]             s: "command failed: cannot run command \"/usr/bin/oc create -f tests/manifests/vm-cirros.yaml -n kubevirt-test-default\": exit status 1",
11:15:38 [check-patch.openshift_3-10.el7.x86_64]         }
11:15:38 [check-patch.openshift_3-10.el7.x86_64]         command failed: cannot run command "/usr/bin/oc create -f tests/manifests/vm-cirros.yaml -n kubevirt-test-default": exit status 1
11:15:38 [check-patch.openshift_3-10.el7.x86_64]     not to have occurred

fom the log it can be it:
(https://jenkins.ovirt.org/job/kubevirt_kubevirt-ansible_standard-check-pr/1696//artifact/check-patch.openshift_3-10.el7.x86_64/vm_logs/on_exit/lago-master/_var_log/containers/virt-controller-567c4c757b-n4s6h_kube-system_virt-controller-c10bbe2385d4a5fc227ab296ccfc08f1b63c52de830049622868d217675e25fd.log)

2018-11-07T04:12:47.690077507-05:00 stderr F {"component":"virt-controller","level":"info","msg":"reenqueuing VirtualMachineInstance kubevirt-test-system/vm-cirros","pos":"vmi.go:199","reason":"Operation cannot be fulfilled on virtualmachineinstances.kubevirt.io \"vm-cirros\": the object has been modified; please apply your changes to the latest version and try again","service":"http","timestamp":"2018-11-07T09:12:47.690006Z"}

maybe rerun it and see if it reproduce.

**Comment by gbenhaim** [comment]
@ILpinto regarding the sidecar test:

1. Can we update the fedora image to fc 28/9 ? fc27 isn't supported anymore.
2. I think that the timeout should be increased 

```
11:13:42 [check-patch.openshift_3-10.el7.x86_64] ��� Failure [647.221 seconds]
11:13:42 [check-patch.openshift_3-10.el7.x86_64] VMI with sidecar hook test
11:13:42 [check-patch.openshift_3-10.el7.x86_64] /root/go/src/kubevirt.io/kubevirt-ansible/tests/vm_with_sidecar_hook_test.go:19
11:13:42 [check-patch.openshift_3-10.el7.x86_64]   Check package installtion with hook
11:13:42 [check-patch.openshift_3-10.el7.x86_64]   /root/go/src/kubevirt.io/kubevirt-ansible/tests/vm_with_sidecar_hook_test.go:23
11:13:42 [check-patch.openshift_3-10.el7.x86_64]     will succeed [It]
11:13:42 [check-patch.openshift_3-10.el7.x86_64]     /root/go/src/kubevirt.io/kubevirt-ansible/tests/vm_with_sidecar_hook_test.go:24
11:13:42 [check-patch.openshift_3-10.el7.x86_64] 
11:13:42 [check-patch.openshift_3-10.el7.x86_64]     Expected error:
11:13:42 [check-patch.openshift_3-10.el7.x86_64]         <expect.TimeoutError>: 360000000000
11:13:42 [check-patch.openshift_3-10.el7.x86_64]         expect: timer expired after 360 seconds
11:13:42 [check-patch.openshift_3-10.el7.x86_64]     not to have occurred

**Comment by ILpinto** [comment]
@gbenhaim 
1. Sure can you share image for fc 29 that I can use?
2. I can increase the timeout - no problem.

**Comment by gbenhaim** [comment]
@cynepco3hahue Where can we can fc28/9 vm images for kubevirt's vmi?

**Pull request merged**
