### PR TITLE
Version bump 0.11

### PR DESCRIPTION
**Pull request by booxter**
**What this PR does / why we need it**: This PR bumps kubevirt version deployed to 0.11.0 as well as syncs vendor/* to 0.11.0.

I just had a QE engineer deployed incorrect (old) version of kubevirt with these playbooks because default is still 0.9.6.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Bump default kubevirt version to 0.11.0
```

### CODE REVIEW

**Comment by rthallisey** [comment]
ci test please

**Comment by dankenigsberg** [comment]
@cynepco3hahue with pr #523 merged, this one  should be dropped, right?

**Comment by cynepco3hahue** [comment]
> @cynepco3hahue with pr #523 merged, this one should be dropped, right?

Yes.

**Pull request closed without merging**
