### PR TITLE
Fix curlReq redeclared issue

### PR DESCRIPTION
**Pull request by duyanyan**
**What this PR does / why we need it**:
Use anonymous function to fix curlReq redeclared issue

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #
when running all the tests in the repo, separated functions for curlReq will cause below error:

tests/networkpolicy_test.go:103:75: curlReq redeclared in this block
  previous declaration at tests/network_migration_test.go:152:75

use anonymous function instead

**Special notes for your reviewer**:

**Release note**:

```release-note
none
```

### CODE REVIEW

**Comment by sHaggYcaT** [comment]
Thank you Yan for quick fix

**Comment by fromanirh** [comment]
not sure I fully understand the context, but the code looks reasonnable

**Comment by sHaggYcaT** [comment]
> not sure I fully understand the context, but the code looks reasonnable

Same for me.

**Comment by ksimon1** [comment]
With this change you will have two anonymous almost identical functions. Can you make the function more generic and use it in both cases?

**Pull request closed without merging**
