### PR TITLE
automation: Set default storage role to storage-glusterfs

### PR DESCRIPTION
**Pull request by jarrpa**
Signed-off-by: Jose A. Rivera <jarrpa@redhat.com>

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically.
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by gbenhaim** [comment]
ci add to whitelist

**Comment by aglitke** [comment]
Since this is the default storage we are recommending, we should be deploying and testing it by default.

**Comment by jarrpa** [comment]
@aglitke Don't approve these changes, thus far they're not working. :)

**Comment by aglitke** [comment]
So this is only failing on ocp-3.7.  How long are we holding onto that platform?  @jarrpa are you aware of any changes in openshift-ansible gluster playbooks that would break on 3.7?

**Comment by jarrpa** [comment]
OCP 3.7 will be supported until 3.11 comes out. I am not aware of any differences between 3.9 and 3.7 openshift-ansible that would cause this kind of failure.

**Comment by nellyc** [comment]
@aglitke honestly I dont see the point in testing on ocp-3.7. we will get much more value by testing on origin-3.10

**Comment by jarrpa** [comment]
@nellyc If there is going to be an official statement that kubevirt will only be supported on a subset of OpenShift versions that are currently under support, that's fine. In that case, the 3.7 test should be removed.

I've updated the commits to remove the debug code. This should pass 3.9, but I'll want to verify that this actually worked in the ansible output

**Comment by rthallisey** [comment]
@jarrpa I think we can close this. https://github.com/kubevirt/kubevirt-ansible/pull/241 is passing in CI with gluster enabled by default.

**Comment by jarrpa** [comment]
@rthallisey Now that the CI is passing over there, more than happy to close this!

**Pull request closed without merging**
