### PR TITLE
Remove Vagrant files

### PR DESCRIPTION
**Pull request by alexxa**
@cynepco3hahue said Vagrant is not used in this project and can be removed.

### CODE REVIEW

**Comment by gbenhaim** [comment]
The failure is unrelated, it was caused by unavailability of Centos' repos:
`Failure talking to yum: Cannot find a valid baseurl for repo: base/7/x86_64`

**Comment by gbenhaim** [comment]
@alexxa config.yml can be also removed (it's another config for vagrant).

**Comment by alexxa** [comment]
@gbenhaim Removed, thanks.

**Comment by gbenhaim** [comment]
The CI failure of Openshift 3-9 is unrelated.

**Pull request merged**
