### PR TITLE
CDI virtctl upload

### PR DESCRIPTION
**Pull request by shiywang**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

/assign @aglitke

### CODE REVIEW

**Comment by shiywang** [comment]
@nellyc this pr build on top of https://github.com/kubevirt/kubevirt-ansible/pull/473

**Comment by shiywang** [comment]
ci test please

**Comment by shiywang** [comment]
ci test please

**Comment by ILpinto** [comment]
@shiywang 

I see that the vm in sidecar test failed to run since there are no resources on the nodes:
PodScheduled False 0001-01-01 00:00:00 +0000 UTC 2018-11-27 04:36:36 +0000 UTC Unschedulable 0/3 nodes are available: 1 Insufficient devices.kubevirt.io/kvm, 1 Insufficient devices.kubevirt.io/tun, 1 Insufficient devices.kubevirt.io/vhost-net, 1 node(s) didn't match node selector, 2 Insufficient memory.}] Scheduling [] <nil>}

I see also that there are running vms from other tests which should be removed. 
Running vms:
virt-launcher-testvmiqcbmpvm777978g84npmrqz7mjgtml2ccwbwdtx5b9n	 Pod phase: Running
virt-launcher-testvmih5qc6pxkmjfstn8sv2xkhktl2w2k5nm77dcdrk2z96	 Pod phase: Running
virt-launcher-test-vm-nv2sc	 Pod phase: Running
virt-launcher-memoryovercommit-mz68j	 Pod phase: Running
virt-launcher-headlesstest-km6zh	 Pod phase: Running
virt-launcher-headlessandmemoryovercommit-xgr7w	 Pod phase: Running
Pending vms:
virt-launcher-vmi-with-sidecar-hook-9qz64	 Pod phase: Pending

I will add to all virt test remove of the vmis.

Israel

**Comment by ILpinto** [comment]
@shiywang 
https://github.com/kubevirt/kubevirt-ansible/pull/486

**Comment by shiywang** [comment]
[cnv-qe-jenkins@cnv-executor-dollierp kubevirt-ansible]$ make test
hack/run-tests.sh
STEP: clean up cirros Image...
Running Suite: Tests Suite
==========================
Random Seed: 1541336879
Will run 3 of 34 specs

SSSSSSSSSSSSSSSSSSSSSSS{"command":"/usr/local/bin/virtctl image-upload --image-path=/tmp/test.img --pvc-name=vm-upload-test-route --pvc-size=500Mi --uploadproxy-url=https://cdi-uploadproxy-cdi.cloudapps.example.com --insecure -n cdi","component":"","level":"error","msg":"command failed: cannot run command","output":"Using existing PVC cdi/vm-upload-test-route\nUploading data to https://cdi-uploadproxy-cdi.cloudapps.example.com\n\n\r 0 B / 12.13 MiB [-----------------------------------------------------------------------------------------------]   0.00%\r 832.00 KiB / 12.13 MiB [=====\u003e-------------------------------------------------------------------------------]   6.70% 0s\n\nUnexpected return value 500\n","pos":"utils.go:2345","reason":"exit status 1","stderr":"","timestamp":"2019-03-13T01:48:11.045632Z"}

------------------------------
• [SLOW TEST:28.678 seconds]
CDI Upload
/root/go/src/kubevirt.io/kubevirt-ansible/tests/cdi_upload_test.go:14
  virtctl upload using openshift route
  /root/go/src/kubevirt.io/kubevirt-ansible/tests/cdi_upload_test.go:26
    will be successful, create again will prompt already exist
    /root/go/src/kubevirt.io/kubevirt-ansible/tests/cdi_upload_test.go:49
------------------------------
{"command":"/usr/local/bin/virtctl image-upload --image-path=/tmp/test.img --pvc-name=vm-upload-test-port-forward --pvc-size=500Mi --uploadproxy-url=https://localhost:18443 --insecure -n cdi","component":"","level":"error","msg":"command failed: cannot run command","output":"Using existing PVC cdi/vm-upload-test-port-forward\nUploading data to https://localhost:18443\n\n\r 0 B / 12.13 MiB [-----------------------------------------------------------------------------------------------]   0.00%\r 10.69 MiB / 12.13 MiB [===========================================================================\u003e----------]  88.13% 0s\n\nUnexpected return value 500\n","pos":"utils.go:2345","reason":"exit status 1","stderr":"","timestamp":"2019-03-13T01:48:35.917621Z"}
• [SLOW TEST:23.451 seconds]
CDI Upload
/root/go/src/kubevirt.io/kubevirt-ansible/tests/cdi_upload_test.go:14
  virtctl upload using kubectl port-forward
  /root/go/src/kubevirt.io/kubevirt-ansible/tests/cdi_upload_test.go:76
    will be successful, create again will prompt already exist
    /root/go/src/kubevirt.io/kubevirt-ansible/tests/cdi_upload_test.go:106
------------------------------
{"command":"/usr/local/bin/virtctl image-upload --image-path=/tmp/test.img --pvc-name=vm-upload-test-port-forward1 --pvc-size=500Mi --uploadproxy-url=https://invalid --insecure -n cdi","component":"","level":"error","msg":"command failed: cannot run command","output":"Using existing PVC cdi/vm-upload-test-port-forward1\nUploading data to https://invalid\n\n\r 0 B / 12.13 MiB [-----------------------------------------------------------------------------------------------]   0.00%\r 0 B / 12.13 MiB [--------------------------------------------------------------------------------------------]   0.00% 0s\n\nPost https://invalid/v1alpha1/upload: dial tcp: lookup invalid on 172.16.0.21:53: no such host\n","pos":"utils.go:2345","reason":"exit status 1","stderr":"","timestamp":"2019-03-13T01:48:36.694483Z"}
•SSSSSSSS
Ran 3 of 34 Specs in 65.635 seconds
SUCCESS! -- 3 Passed | 0 Failed | 0 Pending | 31 Skipped PASS | FOCUSED

**Comment by shiywang** [comment]
```
13:01:46 Failure summary:
13:01:46 
13:01:46 
13:01:46   1. Hosts:    localhost
13:01:46      Play:     Deploy kubevirt role
13:01:46      Task:     Wait until virt-operator is running
13:01:46      Message:  Failed without returning a message.
13:01:46 + on_exit /dev/shm/ost/deployment-openshift false
13:01:46 + set +e
13:01:46 + local run_path=/dev/shm/ost/deployment-openshift
13:01:46 + local skip_cleanup=false
13:01:46 + print_resources_usage /dev/shm/ost/deployment-openshift
13:01:46 + local run_path=/dev/shm/ost/deployment-openshift
13:01:46 + echo 'FS info:'
13:01:46 FS info:
13:01:46 + df -h
13:01:46 Filesystem      Size  Used Avail Use% Mounted on
13:01:46 /dev/sda3       908G   86G  822G  10% /
13:01:46 tmpfs            55G   20G   36G  37% /dev/shm
13:01:46 tmpfs            55G   16M   55G   1% /run/libvirt
13:01:46 + echo 'RAM info:'
13:01:46 RAM info:
13:01:46 + free -h
13:01:46               total        used        free      shared  buff/cache   available
13:01:46 Mem:           109G         13G         34G         19G         62G         75G
13:01:46 Swap:           23G         40M         23G
13:01:46 + echo 'Prefix size:'
```

**Comment by shiywang** [comment]
close this since I assume it's not relevent anymore

**Pull request closed without merging**
