### PR TITLE
remove multus conf on deprovision

### LINKED ISSUE #477: Can not spawn new containers after removing multus pods
When multus is removed, then there are still hanging configuration files on every node.
For example `/etc/cni/net.d/00-multus.conf` .
Presence of this file causes that you can not spawn any new pod after multus removal ...

Note this is clone of https://bugzilla.redhat.com/show_bug.cgi?id=1651693 .

**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**: No pod can be spawned after multus removal 

**What you expected to happen**: I can spawn new pod

**How to reproduce it (as minimally and precisely as possible)**:
Deploy kubevirt with apb, and then deprovision it. Then try to schedule any new pod ...

**Anything else we need to know?**:

brew2-virtualization-depr-7hltt     bundle-f2366e95-3990-47c2-aa06-4b77829c8cc3                  0/1       ContainerCreating   0          23m

In events I can read:
  Warning  FailedCreatePodSandBox  3m (x79 over 21m)  kubelet, cnv-executor-ysegev-node1.example.com  (combined from similar events): Failed create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_bundle-f2366e95-3990-47c2-aa06-4b77829c8cc3_brew2-virtualization-depr-7hltt_a4585a2c-ecd0-11e8-b487-fa163eeeea38_0(bfdfc5584571af9e321b847573746f5dc00612d0da3d2a135eca46c7d24c733c): Multus: Err in loading K8s Delegates k8s args: Multus: Err in getting k8s network from pod: getPodNetworkAnnotation: failed to query the pod bundle-f2366e95-3990-47c2-aa06-4b77829c8cc3 in out of cluster comm: Unauthorized

**Environment**:
- kubevirt-ansible version(use `git rev-parse HEAD`):
- KubeVirt version (use `virtctl version`):
- OpenShift/Kubernetes version (use `kubectl version` or `oc versions`):
- VM or VMI specifications:
- Ansible version  (use `ansible --version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by leongold**
**What this PR does / why we need it**:
Bug fix

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #477 

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically.
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by leongold** [comment]
ci test please

**Comment by leongold** [comment]
@gbenhaim whitelist please

**Comment by gbenhaim** [comment]
ci add to whitelist

**Pull request merged**
