### PR TITLE
Targeting proper host groups in playbooks.

### PR DESCRIPTION
**Pull request by dcritch**
This change will narrow the scope of playbook runs to the relevant
nodes in an inventory, rather than the more broad 'all'.

This addresses issues #188, #86, #195 and #239

### CODE REVIEW

**Comment by aglitke** [comment]
@copejon please review

**Comment by dcritch** [comment]
Currently some playbooks expect to be run on localhost, while others are targeting the nodes. There was a previous issue to get that addressed and one playbook (storage.yml) has been merged with the switch.

Following the openshift-ansible approach, playbooks should run on the nodes/master0/etc and not localhost. It is a toss up between making it more apb compatible vs. e.g. requiring that openshift clients are installed on the ansible or tower server running the jobs.

I checked and of the 9 files changed, 3 are of the localhost->master[0] variety, while the others are going from `all` or similar to something more targeted.

I can:
1/ Remove those 3 files that are up to debate out of this PR and leave the rest until a final decision has been made
2/ Keep the PR as is, and add apb specific playbooks later
3/ Keep the PR as is, and add apb specific playbooks now.

What do you think?

**Comment by dcritch** [comment]
cc @rthallisey @alexxa @lukas-bednar 
Looks like a mess due to a rebase, but I think this one is good to go?

**Comment by lukas-bednar** [comment]
@dcritch could you please rebase it, that we can see what this patch change?

**Comment by dcritch** [comment]
@lukas-bednar I seemed to mess up git real good, so I'm closing this request and opened up a clean one here: https://github.com/kubevirt/kubevirt-ansible/pull/282

**Pull request closed without merging**
