### PR TITLE
Change cni-plugins image to kubevirt/cni-default-plugins

### PR DESCRIPTION
**Pull request by SchSeba**
**What this PR does / why we need it**:
Change cni-plugins image to kubevirt/cni-default-plugins

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
Upload the cni plugins image to the kubevirt organisation in quay

**Release note**:

```release-note
None
```

---
This change is [Reviewable](https://reviewable.io/reviews/kubevirt/kubevirt-ansible/603)

### CODE REVIEW

**Comment by SchSeba** [comment]
@myakove @rthallisey can you please review this PR ?

**Comment by SchSeba** [comment]
Hi @lukas-bednar can you please take a look?

**Comment by SchSeba** [comment]
@myakove @rthallisey can we merge this PR?

**Comment by myakove** [comment]
quay.io/schseba/cni-plugins and quay.io/kubevirt/cni-default-plugins are the same only the name was changed?

**Comment by SchSeba** [comment]
almost this image don't contains an `entrypoint.sh` script so I added the command in the yaml file https://github.com/kubevirt/kubevirt-ansible/pull/603/files#diff-98771fffa0ef325dd0d74e150ed48cabR27

**Pull request merged**
