### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by fabiand**

### CODE REVIEW

**Comment by eedri** [comment]
LGTM :+1:

**Comment by gbenhaim** [comment]
+1

**Comment by lukas-bednar** [comment]
Hi following pr #60 is rewriting almost whole content of README, I incorporated some of these changes there already and some parts are getting removed anyway. If you don't mind I would abandon this change in favor of pr mentioned above.
If you have any extra requirements you can comment there to request it.

@fabiand what do you think ?

**Comment by fabiand** [comment]
wfm!

**Pull request closed without merging**
