### PR TITLE
Add openshift support

### PR DESCRIPTION
**Pull request by karmab**
basic role leveraging the same script with oc commands that in https://github.com/kubevirt/kubevirt/pull/608

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for an this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically.
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organisation's projects.

Note: You might see multiple messages like this showing up on a single PR, this is due to a known bug in the GitHub trigger plugin on Jenkins, the infra team is working on fixing this via new testing flow in the near future, so we'll be able to post a single message per PR.

**Comment by gbenhaim** [comment]
ci add to whitelist

**Comment by gbenhaim** [comment]
ci test please

**Comment by fabiand** [comment]
@karmab thanks for the contribution, gal will take it from here.

**Comment by gbenhaim** [comment]
ci test please

**Comment by fabiand** [comment]
ci test please

**Comment by gbenhaim** [comment]
@karmab Thanks for the contribution.
Can you please take a look on the error:

```
2017-12-15 17:45:15,895 p=31624 u=root |  PLAY [all] *********************************************************************
2017-12-15 17:45:15,949 p=31624 u=root |  TASK [Gathering Facts] *********************************************************
2017-12-15 17:45:30,195 p=31624 u=root |  ok: [lago-node1]
2017-12-15 17:45:32,423 p=31624 u=root |  ok: [lago-node0]
2017-12-15 17:45:32,921 p=31624 u=root |  ok: [lago-master]
2017-12-15 17:45:32,962 p=31624 u=root |  TASK [/home/jenkins/workspace/kubevirt-incubator_kubevirt-ansible_standard-check-pr/kubevirt-ansible/openshift/roles/security : Execute openshift security script] ***
2017-12-15 17:45:52,944 p=31624 u=root |  fatal: [lago-node1]: FAILED! => {
    "changed": true, 
    "failed": true, 
    "rc": 1
}

STDOUT:

error: Missing or incomplete configuration info.  Please login or point to an existing, complete config file:

  1. Via the command-line flag --config
  2. Via the KUBECONFIG environment variable
  3. In your home directory as ~/.kube/config

To view or setup config directly use the 'config' command.
See 'oc adm policy add-scc-to-user -h' for help and examples.
error: Missing or incomplete configuration info.  Please login or point to an existing, complete config file:

  1. Via the command-line flag --config
  2. Via the KUBECONFIG environment variable
  3. In your home directory as ~/.kube/config

To view or setup config directly use the 'config' command.
See 'oc adm policy add-scc-to-user -h' for help and examples.
```

My guess is that `oc login -u system:admin` should be called first.

**Comment by fabiand** [comment]
How does this align with #37 ?

**Comment by gbenhaim** [comment]
@karmab Can we close this PR?

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically.
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by alexxa** [comment]
@karmab @fabiand @cynepco3hahue What is the status of this PR? Is it still valid? WIP?

**Comment by lukas-bednar** [comment]
I am closing this PR since there is no activity for long time, and it also got very behind of current state of repository.
Feel free to reopen it if you want continue.

**Pull request closed without merging**
