### PR TITLE
GlusterFS: increase default snapfactor to prevent cloning issues

### PR DESCRIPTION
**Pull request by nixpanic**
By default the 'snapfactor' is set to 1.0, which means that there is
very little space reserved for modifications to cloned volumes. By
increasing the 'snapfactor' to 3.0, the requested PVC will be backed by
a larger (LVM) thin-pool on the Gluster storage servers and it is less
likely that the thin-pool will run out of space when a few PVCs are
cloned from the original.

The 'snapfactor' option is only available in the external provisioner,
and was introduced with kubernetes-incubator/external-storage#648.

/cc @jarrpa @humblec

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically.
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by gbenhaim** [comment]
ci add to whitelist

**Comment by nixpanic** [comment]
@gbenhaim or @rthallisey could you review+merge this please?

/cc @aglitke

**Comment by rthallisey** [comment]
@nixpanic just needs a rebase then it's good to go

**Comment by nixpanic** [comment]
@rthallisey thanks, should be ready to go now

**Pull request merged**
