### PR TITLE
Update to OKD 3.11

### PR DESCRIPTION
**Pull request by gbenhaim**
Signed-off-by: gbenhaim <galbh2@gmail.com>

```release-note
None
```

### CODE REVIEW

**Comment by gbenhaim** [comment]
ci test please

**Comment by gbenhaim** [comment]
@lukas-bednar yes, I'm hitting the same issue :-\

**Comment by gbenhaim** [comment]
```
00:41:22.692 [check-patch.openshift_3-11.el7.x86_64] Creating cluster ... ID: 96af0b6a133025aefe5b0dc013000c1a
00:41:22.692 [check-patch.openshift_3-11.el7.x86_64] 	Allowing file volumes on cluster.
00:41:22.692 [check-patch.openshift_3-11.el7.x86_64] 	Allowing block volumes on cluster.
00:41:22.692 [check-patch.openshift_3-11.el7.x86_64] 	Creating node lago-master ... ID: ab1bf99f8f0f4a51556601f14ad88ab8
00:41:22.692 [check-patch.openshift_3-11.el7.x86_64] 		Adding device /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_4 ... Unable to add device: Device /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_4 not found.
00:41:22.692 [check-patch.openshift_3-11.el7.x86_64] 	Creating node lago-node0 ... ID: d1fd77c535b6af1ffacce444c2993f00
00:41:22.692 [check-patch.openshift_3-11.el7.x86_64] 		Adding device /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_3 ... Unable to add device: Device /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_3 not found.
00:41:22.692 [check-patch.openshift_3-11.el7.x86_64] 	Creating node lago-node1 ... ID: bba361142e3063409bf26f79944d2318
00:41:22.692 [check-patch.openshift_3-11.el7.x86_64] 		Adding device /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_3 ... Unable to add device: Device /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_3 not found.
```

@lukas-bednar Do you think it's because we stopped mounting `/dev`?
How do you specify to gluster which block devices to use?

**Comment by gbenhaim** [comment]
ci test please

**Comment by gbenhaim** [comment]
Not sure why but the job getting stuck while trying to remove `kubevirt-web-ui`.

**Comment by gbenhaim** [comment]
@mareklibra Can you please check why `kubevirt_web_ui : Remove kubevirt-web-ui project` getting stuck?

@lukas-bednar Have you seen this error before?

**Comment by mareklibra** [comment]
@gbenhaim , I'm not facing this issue in my test env. Maybe deadlock somewhere waiting for an object to be removed. I'll do more thorough testing in a few days as I'm recently writing an Operator reusing this code, so I'll try to find the cause then.

The `timeout` hotfix looks good to me in the meantime.

**Comment by gbenhaim** [comment]
@mareklibra The error is very strange:

```
01:11:12.364 TASK [kubevirt_web_ui : Remove kubevirt-web-ui project] ************************
01:11:12.366 Sunday 09 December 2018  11:16:03 +0000 (0:00:00.123)       0:00:26.268 ******* 
01:11:12.632 fatal: [lago-master]: FAILED! => {
01:11:12.633     "changed": true, 
01:11:12.635     "cmd": "timeout -k 1m 5m \"oc delete project kubevirt-web-ui\"", 
01:11:12.636     "delta": "0:00:00.021742", 
01:11:12.637     "end": "2018-12-09 06:16:04.381245", 
01:11:12.638     "rc": 127, 
01:11:12.639     "start": "2018-12-09 06:16:04.359503"
01:11:12.639 }
01:11:12.639 
01:11:12.639 STDERR:
01:11:12.639 
01:11:12.639 timeout: failed to run command 'oc delete project kubevirt-web-ui': No such file or directory
```

**Comment by gbenhaim** [comment]
@mareklibra OK, now the output looks better:

```
01:06:19.165 TASK [kubevirt_web_ui : Remove kubevirt-web-ui project] ************************
01:06:19.165 Sunday 09 December 2018  13:00:46 +0000 (0:00:00.054)       0:00:26.021 ******* 
01:11:25.916 fatal: [lago-master]: FAILED! => {
01:11:25.916     "changed": true, 
01:11:25.916     "cmd": "timeout -k 1m 5m \"oc\" delete project \"kubevirt-web-ui\"", 
01:11:25.916     "delta": "0:05:00.029068", 
01:11:25.916     "end": "2018-12-09 08:05:46.753057", 
01:11:25.916     "rc": 124, 
01:11:25.916     "start": "2018-12-09 08:00:46.723989"
01:11:25.916 }
01:11:25.916 
01:11:25.916 STDOUT:
01:11:25.916 
01:11:25.916 project.project.openshift.io "kubevirt-web-ui" deleted
01:11:25.916 
01:11:25.916 
01:11:25.916 MSG:
01:11:25.916 
01:11:25.916 non-zero return code
01:11:25.916 ...ignoring
```

**Comment by gbenhaim** [comment]
@SchSeba I had to remove skydive since it still getting killed by OOM killer.
@ILpinto sidecar test failed on a timeout on every second run of the CI (even after I raised the timeout to 720 sec), I had to set it on pending mode.

@lukas-bednar @rthallisey can you please review?

**Comment by SchSeba** [comment]
@gbenhaim Can you please tell me how much ram the machine have? because I was able to deploy the skydive on a vm inside my laptop.

I am not feeling so good to just disable this feature on not test it

**Comment by gbenhaim** [comment]
@SchSeba We have 0ne master with 4GB and two nodes with 3GB each.
But don't forget that we also deploy gluster, kubevirt, kubevirt-web-ui and vms for the tests.

**Comment by SchSeba** [comment]
@gbenhaim There is no way we can upgrade the environment to something like 6 or 8 GB each?

**Comment by ILpinto** [comment]
@gbenhaim 
The PR https://github.com/kubevirt/kubevirt-ansible/pull/486 
should fix it. please see if you can merge it and not move it to pending.

**Comment by gbenhaim** [comment]
@SchSeba One of the requirements from the env is to be able to run it on an average laptop.
Today the env can be run on a 12GB laptop, and I think that we should keep it as it is.

**Comment by gbenhaim** [comment]
@ILpinto I don't see how https://github.com/kubevirt/kubevirt-ansible/pull/486 will make the test shorter.

**Comment by SchSeba** [comment]
@gbenhaim I have no problem to disable this on a laptop for local tests but I will like to leave it on for every PR.
There is a way to change the configuration when you run local?

**Comment by lukas-bednar** [comment]
>@mareklibra Can you please check why kubevirt_web_ui : Remove kubevirt-web-ui project getting stuck?
>
>@lukas-bednar Have you seen this error before?

Yes have same issue on my environments from beginning. I opened bug about it here: https://bugzilla.redhat.com/show_bug.cgi?id=1651720

**Comment by lukas-bednar** [comment]
LGTM!

**Pull request merged**
