### PR TITLE
[WIP] Storage: Add storage-cinder role

### PR DESCRIPTION
**Pull request by kirankt**
The storage-cinder role deploys a self-contained Cinder storage environment consisting of a Cinder, RabbitMQ and MariaDB. MariaDB currently runs as a privileged pod requiring hostPath to store persistent data. This is not a long-term solution. We will focus on moving away from this model. RabbitMQ pod is not clustered and doesn't have any particular storage requirements.

This role currently supports Ceph and XtremIO backends. NetApp backend is coming soon.

/cc @rthallisey @aglitke

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically.
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by lukas-bednar** [comment]
ci add to whitelist

**Comment by aglitke** [comment]
ci add to whitelist

**Comment by kirankt** [comment]
Closing the PR in favor of Ansible Galaxy role method.

**Pull request closed without merging**
