### PR TITLE
Update KubeVirt to v0.7.0

### PR DESCRIPTION
**Pull request by cynepco3hahue**
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

### CODE REVIEW

**Comment by shiywang** [comment]
if we merge #294  and #295 together ci probably will pass i guess

**Comment by cynepco3hahue** [comment]
Ok, and we have a problem, `v0.7.0-alpha.3` introduced KVM device plugin that does not work on versions < `3.10`, I will add configMap with `useEmulation` flag to avoid the problem

**Comment by lukas-bednar** [comment]
Test is failing to start VM
```
hack/run-tests.sh

Running Suite: Tests Suite

==========================

Random Seed: 152994112

Will run 2 of 2 specs

•level=info timestamp=2018-06-25T15:38:46.519858Z pos=utils.go:236 component=tests msg="Created virtual machine pod virt-launcher-testvmi4bsst-m4csc"
------------------------------

•... Timeout [45.203 seconds]

Sanity

/root/go/src/kubevirt.io/kubevirt-ansible/tests/sanity_test.go:13

  Creating a VM

  /root/go/src/kubevirt.io/kubevirt-ansible/tests/sanity_test.go:27

    should start it [It]

    /root/go/src/kubevirt.io/kubevirt-ansible/tests/sanity_test.go:33

    Timed out

    /root/go/src/kubevirt.io/kubevirt-ansible/tests/sanity_test.go:33

------------------------------

Waiting for namespace kubevirt-test-default to be removed, this can take a while ...

Waiting for namespace kubevirt-test-alternative to be removed, this can take a while ...

Summarizing 1 Failure:

[Timeout...] Sanity Creating a VM [It] should start it 

/root/go/src/kubevirt.io/kubevirt-ansible/tests/sanity_test.go:33

Ran 2 of 2 Specs in 52.336 seconds

FAIL! -- 1 Passed | 1 Failed | 0 Pending | 0 Skipped --- FAIL: TestTests (52.34s)
```

**Comment by shiywang** [comment]
I filed an issue about this before: https://github.com/kubevirt/kubevirt-ansible/issues/249, this is not only happened in CI, but our executor environment as well.

**Comment by cynepco3hahue** [comment]
@lukas-bednar @shiywang We currently have alpha4 build, that has the fix for SELinux issue, will update this PR accordingly.

**Comment by cynepco3hahue** [comment]
Hm it still failed to start a VM, will check it locally.

**Comment by cynepco3hahue** [comment]
@lukas-bednar @shiywang Ok looks like it still dependents on device plugin also with `useEmulation` flag(it is waiting for TUN device to be available on nodes). So we need to move kubevirt-ansible CI to work with OpenShift 3.10, do we have some work in this direction?

**Comment by gbenhaim** [comment]
@cynepco3hahue The work is blocked because there are no RPMs for Openshift 3.10.
Do Kubevirt CI runs on Openshift 3.10?

**Comment by cynepco3hahue** [comment]
@gbenhaim yes, I created RPM's from OpenShift repo from the tag `v3.10.0-rc.0`

**Comment by gbenhaim** [comment]
@cynepco3hahue Can you share a link to the repo?

**Comment by gbenhaim** [comment]
@cynepco3hahue @lukas-bednar @rthallisey Is this PR blocked because we use OC 3.10? Or there is a fix on Kubevirt for this issue?

**Comment by cynepco3hahue** [comment]
@gbenhaim It blocked because CI uses OpenShift 3.9

**Comment by cynepco3hahue** [comment]
@shiywang We can wait until next release, but I prefer do not set commit hash, it difficult to understand with what KubeVirt release kubevirt-ansible works.

**Comment by shiywang** [comment]
@cynepco3hahue okay, I got it

**Comment by gbenhaim** [comment]
ci test please

**Comment by rthallisey** [comment]
ci test please

**Comment by cynepco3hahue** [comment]
ci test please

**Comment by cynepco3hahue** [comment]
@gbenhaim Does standard CI nodes support nested virtualization?

**Comment by gbenhaim** [comment]
@cynepco3hahue yes

**Comment by cynepco3hahue** [comment]
Ok I added some printing info and I can see that the VM can not start because of
```
KVM devices are required for testing, but are not present on cluster nodes
```

**Comment by cynepco3hahue** [comment]
@gbenhaim Do I have a possibility to check nodes created by standard CI?

**Comment by gbenhaim** [comment]
@cynepco3hahue The logs of the VMs can be found here: https://jenkins.ovirt.org/job/kubevirt_kubevirt-ansible_standard-check-pr/954//artifact/exported-artifacts/check-patch.openshift_3-10.el7.x86_64/vms_logs/

**Comment by cynepco3hahue** [comment]
I found the problem with `KVM devices are required for testing, but are not present on cluster nodes`, https://github.com/kubevirt/kubevirt/pull/1270 will solve it.

**Comment by nellyc** [comment]
@gbenhaim can we mark the std ci as not required, otherwise it fails on 3.9 failure
which is expected

**Comment by cynepco3hahue** [comment]
@lukas-bednar @shiywang @gbenhaim Tests passed on os-3.10, so I think we can merge it.

**Pull request merged**
