### PR TITLE
Removed old v2v tests

### PR DESCRIPTION
**Pull request by vatsalparekh**
**What this PR does / why we need it**:
Removed old v2v tests

**Special notes for your reviewer**:
just merge it

**Release note**:

```release-note
Removed old v2v tests
```

### CODE REVIEW

**Comment by vatsalparekh** [comment]
PTAL @shiywang @lukas-bednar @nellyc

**Comment by vatsalparekh** [comment]
CI failure here would not be related to the removal of these tests

**Comment by vatsalparekh** [comment]
ci test please

**Comment by tareqalayan** [comment]
ci test please

**Comment by tareqalayan** [comment]
looks good

**Pull request merged**
