### PR TITLE
WIP: test skipping

### PR DESCRIPTION
**Pull request by eedri**
Signed-off-by: Eyal Edri <eedri@redhat.com>

### CODE REVIEW

**Comment by eedri** [comment]
looks like adding [skip ci] works and doesn't trigger CI.

**Comment by eedri** [comment]
dropping the [skip ci] from title to check

**Comment by eedri** [comment]
ci test please

**Comment by alexxa** [comment]
@eedri CI wasn't triggered because you updated md doc. CI ignores changes in docs, see PR #81. Update code file, use [skip ci] and try again.

**Comment by eedri** [comment]
I don't think this is correct, the feature to not run CI if you update .md files is in the check-patch.sh script, which means Jenkins job has to run to get to that code.
In this case no job run, so its not possible it could know which file was changed.

But I'll update code as well to prove it.

**Comment by alexxa** [comment]
This PR was updated 3 times (doc change skip ci, title change, code change skip ci). I see 2 jenkins jobs were started.

**Comment by eedri** [comment]
They were started because I removed the skip CI on previous PR, did it
trigger again on the last one as well ?

**Comment by alexxa** [comment]
I do think so. Because I remember that I pushed my first commit on this repo, and used [skip ci], but CI was triggered anyway. Then I tried [ci skip], it din't work as I expected too. I opened an issue about it: #76 and originally titled it "add [ci skip] and [skip ci] in CI" and see it's description - meaning [skip ci] flag didn't work for me back then. Does it really work for you now? If so, I don't understand how and what changed since I reported that issue.

**Comment by eedri** [comment]
Hi,
I can think on a few options why it didn't pass in the past.
First, is it possible that [skip-ci] was used? i.e with a dash(-)? because according to the regex, it looks like only whitespace is supported.

Second, we recently upgraded the GitHub plugin on Jenkins, and I remeber it did have issues, so maybe the upgrade fixed it.

In any case, can you verify it works for you now on a patch with [skip ci] ?

**Comment by eedri** [comment]
closing, this was just for testing purposes.

**Pull request closed without merging**
