### PR TITLE
openshift: Use containerized deployment

### PR DESCRIPTION
**Pull request by gbenhaim**
Will accelerate the deployment process.

closes https://github.com/kubevirt-incubator/kubevirt-ansible/issues/41

Signed-off-by: gbenhaim <galbh2@gmail.com>

### CODE REVIEW

**Comment by lukas-bednar** [comment]
change itself looks good.
can you please try to create vm on such environment and make sure that it is running?
I had a troubles with volumes, The Vm doesn't get scheduled, and get stuck on following error:
```
level=error timestamp=2018-01-19T12:42:27.657875Z pos=vm.go:168 component=virt-controller service=http namespace=myproject name=testvm kind= uid=d2a013b9-fd15-11e7-9407-001a4a16982c reason="pods \"virt-launcher-testvm-----\" is forbidden: unable to validate against any security context constraint: [provider restricted: .spec.securityContext.hostPID: Invalid value: true: Host PID is not allowed to be used spec.volumes[0]: Invalid value: \"hostPath\": hostPath volumes are not allowed to be used spec.volumes[1]: Invalid value: \"hostPath\": hostPath volumes are not allowed to be used provider restricted: .spec.containers[0].securityContext.hostPID: Invalid value: true: Host PID is not allowed to be used]" msg="Defining a target pod for the VM failed."
```
I used used following yamls to start vm.
```
kubevirt/manifests/testing/iscsi-auth-demo-target.yaml
kubevirt/manifests/testing/iscsi-demo-target.yaml
kubevirt/cluster/vm.yaml
```

**Comment by gbenhaim** [comment]
When did you try to create a VM?
https://github.com/kubevirt/kubevirt/pull/640 should fix the permissions issue (was merged last night)

**Comment by gbenhaim** [comment]
ci test please

**Comment by lukas-bednar** [comment]
@gbenhaim I did rebase on it ... I see what might be problem ... I forget apply `manifests/testing/rbac-for-testing.yaml` ... I will try.

**Comment by gbenhaim** [comment]
Do not merge. This change adds ~8 minutes to the job. Need to investigate...

**Comment by gbenhaim** [comment]
@lukas-bednar I suggest using containerized version because it will make it easier to use oc 3.9.
what do you think?

**Comment by lukas-bednar** [comment]
@gbenhaim :+1:

**Pull request merged**
