### PR TITLE
enable CPUNodeDiscovery feature-gate

### PR DESCRIPTION
**Pull request by ksimon1**
**What this PR does / why we need it**:
This PR enables CPUNodeDiscovery feature-gate, which is needed for  https://github.com/kubevirt/kubevirt/pull/1721
@petrkotas, @vladikr, @yanirq please review

**Release note**:
```release-note
enable CPUNodeDiscovery feature-gate 
```

### CODE REVIEW

**Comment by petrkotas** [comment]
@lukas-bednar Can you please do round of review?

**Comment by ksimon1** [comment]
@petrkotas This PR should enable CPUNodeDiscovery feature gate for kubevirt. It should enable the functionality in PR which i put in description.

**Comment by petrkotas** [comment]
Yes, than LGTM.
--
s pozdravem,
Petr Kotas

**Comment by lukas-bednar** [comment]
It looks good to me.

**Pull request closed without merging**
