### PR TITLE
Use released manifests

### PR DESCRIPTION
**Pull request by rthallisey**
fixes: https://github.com/kubevirt/kubevirt-ansible/issues/179

### CODE REVIEW

**Comment by davidvossel** [comment]
fyi, we have a new release incoming to address a major issue that slipped into the v4 release. You'll want to skip v0.4.0 and jump to v0.4.1-alpha.1.

**Comment by rthallisey** [comment]
@davidvossel thanks for the info

**Comment by rthallisey** [comment]
@lukas-bednar @gbenhaim I'm not sure what to do about the 3.7 job. It seems like it's failing to delete some images.

**Comment by alexxa** [comment]
@rthallisey If there was 'a major issue that slipped into the v4 release', do we really want to keep it as an option [here](https://github.com/kubevirt/kubevirt-ansible/pull/181/files#diff-819a6b1c4a998c9deb68760bbb929150R17) and [here](https://github.com/kubevirt/kubevirt-ansible/pull/181/files#diff-a05e100efea07219975d06a6b7d33bf7R10). And why do we need old versions? Why we don't use the 'latest/most recent one' only?

**Comment by fabiand** [comment]
We'll probably do a patch release tomorrow to fix the issue which was discovered in 0.4.0

**Pull request merged**
