### PR TITLE
Update CDI to v1.1.1

### PR DESCRIPTION
**Pull request by shiywang**
Signed-off-by: Shiyang Wang <shiywang@redhat.com>

Since Host-Assisted cloning was introduced in https://github.com/kubevirt/containerized-data-importer/releases/tag/v1.1.0-alpha.1

@copejon @aglitke @jeffvance

### CODE REVIEW

**Comment by aglitke** [comment]
In my view we should wait until a non-alpha cdi release comes out before switching.

**Comment by shiywang** [comment]
ci test this

**Comment by shiywang** [comment]
ci test please

**Comment by gbenhaim** [comment]
Why does it fail?

**Comment by shiywang** [comment]
@gbenhaim might due to https://github.com/kubevirt/kubevirt-ansible/issues/327

**Comment by shiywang** [comment]
once this pr https://github.com/kubevirt/containerized-data-importer/pull/249 got merged, it might fix the problem

**Comment by aglitke** [comment]
From the jenkins log:

```

------------------------------

• [SLOW TEST:5.172 seconds]

Importing and starting a VM using CDI

/root/go/src/kubevirt.io/kubevirt-ansible/tests/cdi/cdi_test.go:12

  PVC with valid image url will succeed

  /root/go/src/kubevirt.io/kubevirt-ansible/tests/cdi/cdi_test.go:23

    the PVC should become bound

    /root/go/src/kubevirt.io/kubevirt-ansible/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:365

------------------------------

KUBECONFIG=/home/jenkins/workspace/kubevirt_kubevirt-ansible_standard-check-pr/kubevirt-ansible/.kube/config /usr/bin/oc get pod -l app=containerized-data-importer -o=jsonpath='{.items[0].status.phase}' -n kubevirt-test-default

Error executing template: array index out of bounds: index 0, length 0. Printing more information for debugging the template:

	template was:

		'{.items[0].status.phase}'

	object given to jsonpath engine was:

		map[string]interface {}{"kind":"List", "apiVersion":"v1", "metadata":map[string]interface {}{"selfLink":"", "resourceVersion":""}, "items":[]interface {}{}}



error: error executing jsonpath "'{.items[0].status.phase}'": array index out of bounds: index 0, length 0

exit status 1
```

It seems there is an issue with the tests.  If the test checks for the importer pod before it was created the query will fail with an index out of range error.  The test should catch this error and try again until the timeout instead of failing immediately.

**Comment by shiywang** [comment]
@aglitke fixed in https://github.com/kubevirt/kubevirt-ansible/pull/331

**Comment by shiywang** [comment]
ci test please

**Comment by aglitke** [comment]
@shiywang Please change this PR to CDI-1.1.1 now that is has been released.

**Comment by shiywang** [comment]
@nellyc @gbenhaim @alexxa @lukas-bednar @aglitke PTAL

**Comment by shiywang** [comment]
@nellyc could you merge it?

**Pull request merged**
