### PR TITLE
Removed use of duplicate namespace in RunCommand function

### LINKED ISSUE #489: kubevirt-ansible tests are running with extra namespace argument
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Expected error:
        <*errors.errorString | 0xc4202562e0>: {
            s: "command failed: cannot run command \"/usr/bin/oc create -f tests/manifests/vm_with_sidecar_hook.yml -n kubevirt-test-default -n kubevirt-test-default\": exit status 1",
        }
        command failed: cannot run command "/usr/bin/oc create -f tests/manifests/vm_with_sidecar_hook.yml -n kubevirt-test-default -n kubevirt-test-default": exit status 1
    not to have occurred

Not required to give `kubevirt-test-default` namespace as RunCommand function takes it by default.

**What you expected to happen**:
Tests should run with the single namespace argument.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
External commands are not confined to an explicit namespace, unless "-n"
argument is added.  Since the original version of the tests.RunCommand()
function did not care about namespaces, it was susceptible to produce
errors that are hard to debug, e.g., creating a VMI in the 'default'
namespace instead of 'kubevirt-test-default'.  The extended version of
the tests.RunCommand() function also automatically adds "-n" argument to
confine the command to tests.NamespaceTestDefault namespace.  If one
would like to run external command in different namespace, e.g.,
tests.NamespaceTestAlternative, I have introduced a new function for
this purpose:

  tests.RunCommandWithNS(namespace, command, args...)

If it is not recommendable to place "-n" as the last argument, e.g., in
case of the 'kubectl exec ... -- ...' command, it is possible to
knock-off the automatic "-n" inclusion by passing an empty string:

  tests.RunCommandWithNS("", command, args...)

### PR DESCRIPTION
**Pull request by adityaramteke**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #489 

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by adityaramteke** [comment]
@gouyang These functions are meant to be used by default namespace `NamespaceTestDefault` and it does not allow us to mention another namespace while using it in the tests. If we want to use or run the test with specific namespace then it's better to go with 'tests.RunCommandWithNS("", command, args...)
' in individual test.

**Comment by gouyang** [comment]
@adityaramteke shiywang suggested to use the `ktests.RunCommandWithNS` in the issue #489, right? I agree with it also. We can wait for more inputs.

**Comment by adityaramteke** [comment]
@gszasz let me know your thoughts.

**Comment by dshchedr** [comment]
We still have duplicate namespaces... for the fix need to remove:
https://github.com/adityaramteke/kubevirt-ansible/blob/d1dccae5d0e36fefa3e6683a9b1da58c51eb76d7/tests/framework/cli_exec.go#L55-L57

**Comment by shiywang** [comment]
@dshchedr Sorry for that, fixing it: https://github.com/kubevirt/kubevirt-ansible/pull/505

**Pull request merged**
