### PR TITLE
add cdi datavolumes and events to clusterroles

### PR DESCRIPTION
**Pull request by shiywang**
Fixes https://github.com/kubevirt/kubevirt-ansible/issues/284
Signed-off-by: Shiyang Wang <shiywang@redhat.com>

### CODE REVIEW

**Comment by shiywang** [comment]
@davidvossel @copejon @jeffvance PTAL

**Comment by shiywang** [comment]
ci test please

**Comment by shiywang** [comment]
@lukas-bednar @gbenhaim PTAL

**Comment by lukas-bednar** [comment]
Looks good to me.

**Comment by shiywang** [comment]
@aglitke PTAL

**Comment by aglitke** [comment]
Shouldn't this be fixed in the CDI-provided manifests first and then those manifests should be imported into kubevirt-ansible?

**Comment by davidvossel** [comment]
> Shouldn't this be fixed in the CDI-provided manifests first and then those manifests should be imported into kubevirt-ansible?

yes.  I acked this as a short-term fix to get cdi working again when they were dealing with cdi release issues.

we should really be pulling the manifests from the CDI project now in the same way kubevirt manifests are done.

**Comment by shiywang** [comment]
Yes, that's also what I mean, and I already created an issue [here](https://github.com/kubevirt/kubevirt-ansible/issues/301).
I think we could merged this first as a short-term fix.
@lukas-bednar @davidvossel @aglitke

**Comment by lukas-bednar** [comment]
Based on discussion and following up with issue #301 , we can merge this PR to make CDI working properly for meanwhile referenced issue is solved.

**Pull request merged**
