### PR TITLE
GlusterFS role fixes

### PR DESCRIPTION
**Pull request by jarrpa**
A few fixes I felt were necessary to the GlusterFS role and related files. I'll note here that the addition of the `heketi_url` variable is to allow this to actually be usable by Kubernetes, since we claim that will happen one day. :)

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically.
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by jarrpa** [comment]
@aglitke If you could, please take a look and rope in anyone else that needs to do so.

**Comment by lukas-bednar** [comment]
ci add to whitelist

**Comment by jarrpa** [comment]
Oops, didn't notice that it was complaining about the branch being out of date. Commits updated.

**Comment by jarrpa** [comment]
@aglitke This looks good to go!

**Pull request merged**
