### PR TITLE
kubevirt: fix condition error on render offline template task

### PR DESCRIPTION
**Pull request by guits**
this condition might fail if the task which registers `offline_templates` is skipped.

Typical error:

```
The conditional check 'offline_templates.stat.exists == True' failed.
The error was: error while evaluating conditional
(offline_templates.stat.exists == True): 'dict object' has no attribute
'stat'
```

The idea is to check if `offline_templates` is skipped before trying to
evaluate `offline_templates.stat.exists`

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically.
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by rthallisey** [comment]
ci test please

**Comment by guits** [comment]
ci test please

**Comment by lukas-bednar** [comment]
ci add to whitelist

**Pull request merged**
