### PR TITLE
remove namespace duplication

### PR DESCRIPTION
**Pull request by shiywang**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dshchedr** [comment]
//cc @lbender

**Comment by dshchedr** [comment]
@lukas-bednar please review and merge

**Comment by lukas-bednar** [comment]
@dshchedr I can not merge that until "Required" tests are successful.

@gbenhaim Could you please take a look at this job ? It seems to be stuck.

**Comment by gbenhaim** [comment]
ci test please

**Comment by lukas-bednar** [comment]
ci test please

**Pull request merged**
