### PR TITLE
Move kubevirt version to v0.8.0

### PR DESCRIPTION
**Pull request by lukas-bednar**
Signed-off-by: Lukas Bednar <lbednar@redhat.com>

### CODE REVIEW

**Comment by lukas-bednar** [comment]
```
[36m@ Cleanup prefix: [32mSuccess[0m (in 0:00:03)[0m
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/__init__.py", line 875, in emit
    self.flush()
  File "/usr/lib64/python2.7/logging/__init__.py", line 835, in flush
    self.stream.flush()
IOError: [Errno 28] No space left on device
Logged from file log_utils.py, line 611
```

**Comment by lukas-bednar** [comment]
ci test please

**Comment by lukas-bednar** [comment]
ci test please

**Comment by gbenhaim** [comment]
@lukas-bednar It looks like the previous failure was caused by a low disk space on the Jenkins slave.

**Comment by lukas-bednar** [comment]
@gbenhaim I still see that :-(

```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/__init__.py", line 875, in emit
    self.flush()
  File "/usr/lib64/python2.7/logging/__init__.py", line 835, in flush
    self.stream.flush()
IOError: [Errno 28] No space left on device
Logged from file log_utils.py, line 611
Took 3097 seconds
```

**Comment by gbenhaim** [comment]
@lukas-bednar I'm handling the space issue.

**Comment by gbenhaim** [comment]
@lukas-bednar https://github.com/kubevirt/kubevirt-ansible/pull/397

**Pull request merged**
