### PR TITLE
move secret file to the right namespace

### PR DESCRIPTION
**Pull request by shiywang**
Fixes: https://github.com/kubevirt/kubevirt-ansible/issues/250

Signed-off-by: Shiyang Wang <shiywang@redhat.com>

@gbenhaim @rthallisey @aglitke @copejon PTAL

### CODE REVIEW

**Comment by copejon** [comment]
lgtm!

**Comment by lukas-bednar** [comment]
failure is not related to patch `Error: Failed to synchronize cache for repo 'updates'`. I will try to rerun it .

**Comment by shiywang** [comment]
ci passed @lukas-bednar @rthallisey @gbenhaim someone could help merge it ? Thanks !!

**Comment by jeffvance** [comment]
lgtm

**Comment by shiywang** [comment]
@lukas-bednar could we merge this one ?

**Pull request merged**
