### PR TITLE
[Virt] VM with sidecar hook test

### PR DESCRIPTION
**Pull request by ILpinto**
Sidecar hook allowing user to configure smbios properties in VM domain XML
annotations:
    # Request the hook sidecar
    hooks.kubevirt.io/hookSidecars: '[{"image": "phoracek/kubevirt-hook-smbios"}]'
    # Overwrite base board manufacturer name
    smbios.vm.kubevirt.io/baseBoardManufacturer: "Radical Edward"

### CODE REVIEW

**Comment by ILpinto** [comment]
ci please test

**Comment by ILpinto** [comment]
ci test please

**Comment by ILpinto** [comment]
@lukas-bednar @gbenhaim 
The compilation of the test failed 
https://jenkins.ovirt.org/job/kubevirt_kubevirt-ansible_standard-check-pr/1598/artifact/check-patch.openshift_3-10.el7.x86_64/generate-tests.log

Can you take a look?
10x

**Comment by gbenhaim** [comment]
@ILpinto you can find the compilation errors in `generate-tests.log`, it's under the `artifacts` link in the ui https://jenkins.ovirt.org/job/kubevirt_kubevirt-ansible_standard-check-pr/1598/artifact/ci_build_summary.html.

The compilation with the following error:

```
# kubevirt.io/kubevirt-ansible/tests
tests/util.go:19:2: log redeclared as imported package name
	previous declaration at tests/util.go:17:2
```

**Comment by ILpinto** [comment]
@lukas-bednar 
please review

**Comment by lukas-bednar** [comment]
LGTM

**Pull request merged**
