### PR TITLE
Add flag kubectl-path

### LINKED ISSUE #349: Add flag kubectl-path for tests in hack/run-tests.sh
Details in http://jenkins.ovirt.org/job/kubevirt_kubevirt-ansible_standard-check-pr/1077//artifact/check-patch.openshift_3-10.el7.x86_64/mock_logs/script/stdout_stderr.log.

The tests is failed at below lines, the root cause is it cannot find kubectl binary, add `-kubectl-path=/usr/bin/kubectl` should fix it.

```
/root/go/src/kubevirt.io/kubevirt-ansible/tests/node_eviction_test.go:94
/root/go/src/kubevirt.io/kubevirt-ansible/tests/node_eviction_test.go:147
```

And it surprise me that it's not happened to oc.

### PR DESCRIPTION
**Pull request by gouyang**
Fixes #349

Signed-off-by: Guohua Ouyang <gouyang@redhat.com>

### CODE REVIEW

**Comment by shiywang** [comment]
I've implemented a lookup function for all the commands downstream, once I update the vendor and submit a pr, it will be fixed in another different appoach, but I think this is another way to fix as well, could you make sure your pr https://github.com/kubevirt/kubevirt-ansible/pull/344 also have this code ? only add parameters here won't make the CI validate the change.

**Comment by nellyc** [comment]
just wondering, why do we need kubectl?
isnt oc & virtctl enough to cover everything we need?

**Comment by shiywang** [comment]
> isnt oc & virtctl enough to cover everything we need?

Yes, oc is enough from functionality perspective.

**Comment by gouyang** [comment]
Change the code to use "oc adm drain" now.

**Pull request closed without merging**
