### PR TITLE
WebUI: fix incorrect set_fact in deprovision

### PR DESCRIPTION
**Pull request by mareklibra**
**Special notes for your reviewer**:
Backport of #598 

**Release note**:

```release-note
BZ 1665391 Fix - proper countdown for Web UI deprovision
```

### CODE REVIEW

**Comment by mareklibra** [comment]
@rthallisey , is this correct target branch for the backport, please? See https://bugzilla.redhat.com/show_bug.cgi?id=1665391

**Comment by mareklibra** [comment]
@rthallisey , is still 1.4 build based on this release-0.12 branch, please? If so, can we merge this backport? Thanks.

**Comment by jelkosz** [comment]
No need to merge this, it is too late in the process. It is enough to have it in the master.

**Comment by rthallisey** [comment]
Closing.  Master fix should be enough.

**Pull request closed without merging**
