### PR TITLE
keeping e2e test in pending mode

### PR DESCRIPTION
**Pull request by adityaramteke**
**What this PR does / why we need it**:
@gbenhaim has missed making one more failure spec Pending 
https://github.com/kubevirt/kubevirt-ansible/pull/469

**Special notes for your reviewer**:
Make sure CI is running successfully 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by gbenhaim** [comment]
@adityaramteke We already merged this change https://github.com/kubevirt/kubevirt-ansible/pull/469 
Thanks!

**Comment by adityaramteke** [comment]
@gbenhaim you have only resolved https://github.com/kubevirt/kubevirt-ansible/blob/master/tests/e2e_test.go#L53
there is one more failure https://github.com/kubevirt/kubevirt-ansible/blob/master/tests/e2e_test.go#L41

**Comment by gbenhaim** [comment]
The first test was failing because the nodes got OOM errors.
We fixed it be limiting the amount of memory Elastic Search (used by Skydive) is using.

**Comment by adityaramteke** [comment]
@gbenhaim you can close it if it is not needed.

**Comment by shiywang** [comment]
https://github.com/kubevirt/kubevirt-ansible/pull/431

**Comment by lukas-bednar** [comment]
This change is not needed anymore

**Pull request closed without merging**
