### PR TITLE
CDI: Update CDI deployment manifest

### PR DESCRIPTION
**Pull request by aglitke**
After adopting cdi-1.1.1 we need to update the manifest used for
deployment in order to apply fixes to RBAC rules.  Also, parameterize
the names of the docker images used by CDI.

Signed-off-by: Adam Litke <alitke@redhat.com>

### CODE REVIEW

**Comment by rthallisey** [comment]
@gbenhaim does CI test with cdi?

**Comment by aglitke** [comment]
@rthallisey @gbenhaim Based on this we can say that cdi was at least smoke tested:
http://jenkins.ovirt.org/job/kubevirt_kubevirt-ansible_standard-check-pr/1213/testReport/(root)/CDI%20Suite/

I think we can merge this?

**Comment by shiywang** [comment]
LGTM

**Pull request merged**
