### PR TITLE
[Virt] Add clear namespace from resources before each test

### PR DESCRIPTION
**Pull request by ILpinto**
Add clean for virt test that remove all resources (vm / vmi /pod /VirtualMachineReplicaSets/ VirtualMachineInstance Secrets/ VirtualMachineInstance Presets / Migration Objects) from 
Namespaces: "kubevirt-test-default" and  "kubevirt-test-alternative"
The clean will be before the test is running.

Release note:
NONE

### CODE REVIEW

**Comment by ILpinto** [comment]
@lukas-bednar 
Can you review and merge 

10x
Israel

**Comment by ILpinto** [comment]
@lukas-bednar 
Can you review and merge

10x
Israel

**Comment by ILpinto** [comment]
Release note:
NONE

**Comment by ILpinto** [comment]
CI please test

**Comment by ILpinto** [comment]
ci test please

**Comment by shiywang** [comment]
@lukas-bednar PTAL

**Pull request merged**
