### PR TITLE
Deploy With Kcli

### PR DESCRIPTION
**Pull request by karmab**
An example of how to:
- use kcli for provisioning of openshift with asb
- how to deploy kubevirt using apb

the corresponding apb code is: 
- at https://github.com/karmab/kubevirt-apb
- published at docker.io/karmab/kubevirt-apb

to make use of the apb, the broker-config config-map of the ansible-service-broker namespace needs to be edited so it contains the following:

```
      - type: "dockerhub"
        name: "karmab"
        url: "https://registry.hub.docker.com"
        org: "karmab"
        tag: "latest"
        white_list:
          - ".*-apb$"
```

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically.
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by gbenhaim** [comment]
1. Don't we want to move the code which builds the APB to this repo? I would like that from this repo, a verified Kubevirt APB will be published, so other users can consume it.

2. Which versions of Openshift and ASB are being used and how they can be changed (can you please add a README with your answer)?

3. Can you please add a README with a link to Kcli documentation?

4. Don't we want to install the ansible modules of Kcli from ansible-galaxy?

5. The dynamic inventory script of Kcli shouldn't be shipped with Kcli?

**Comment by alexxa** [comment]
@karmab what is the status of this PR, please? WIP?

**Comment by lukas-bednar** [comment]
I am closing this PR since there is no activity for long time, and it also got very behind of current state of repository.
Feel free to reopen it if you want continue.

**Pull request closed without merging**
