### PR TITLE
Add kind and apiGroup to ClusterRoleBinding.roleRef

### PR DESCRIPTION
**Pull request by qwang1**
Fixed: https://github.com/kubevirt/kubevirt-ansible/issues/211

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically.
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by qwang1** [comment]
Now clusterrolebinding  "glusterfile-provisioner" can be created.
```
STDOUT:

secret "kubevirt-heketi-secret" unchanged
storageclass "kubevirt" configured
clusterrole "glusterfile-provisioner-runner" configured
serviceaccount "glusterfile-provisioner" unchanged
clusterrolebinding "glusterfile-provisioner" created
```

**Comment by lukas-bednar** [comment]
ci add to whitelist

**Comment by nellyc** [comment]
@qwang1  ping

**Comment by nellyc** [comment]
@alexxa it means nobody touched this PR for 2 months
i was wondering if it is still relevant
if it is, it needs to get approvals and than can be merged

**Comment by lukas-bednar** [comment]
@nellyc it looks good to me, but I would like to get approval of somebody from storage team.
@aglitke Can you please take a look ?

**Comment by shiywang** [comment]
I'm okay with this change, but seems external_provisioner=true has a new problem here: https://github.com/kubevirt/kubevirt-ansible/issues/296

**Pull request closed without merging**
