### PR TITLE
Suport jinjia template for CDI

### PR DESCRIPTION
**Pull request by shiywang**
also related to https://github.com/kubevirt/containerized-data-importer/pull/457 kubevirt/kubevirt-ansible#377

### CODE REVIEW

**Comment by shiywang** [comment]
@aglitke @rthallisey PTAL

**Comment by shiywang** [comment]
ci test please

**Comment by shiywang** [comment]
the error message is because 
```
TASK [cdi : Download CDI Template] *********************************************
Monday 08 October 2018  04:05:40 +0000 (0:00:00.649)       0:33:41.266 ******** 
fatal: [lago-master]: FAILED! => {
    "changed": false
}

MSG:

Destination /home/jenkins/workspace/kubevirt_kubevirt-ansible_standard-check-pr/kubevirt-ansible/roles/cdi/templates does not exist
	to retry, use: --limit @/home/jenkins/workspace/kubevirt_kubevirt-ansible_standard-check-pr/kubevirt-ansible/playbooks/automation/check-patch.retry
```
I think this is similar to `kubevirt_template_dir`, where do we pre set this dir in lago env ? @gbenhaim

**Comment by shiywang** [comment]
ci test please

**Comment by shiywang** [comment]
@rthallisey @gbenhaim @aglitke PTAL

**Comment by rthallisey** [comment]
lg2m.  Rebase and we can merge

**Comment by shiywang** [comment]
@gbenhaim could you help to merge?

**Comment by rthallisey** [comment]
@shiywang one more rebase :)

**Comment by shiywang** [comment]
@rthallisey PTAL

**Pull request merged**
