### PR TITLE
run-tests.sh: make paths to binaries configurable

### PR DESCRIPTION
**Pull request by lukas-bednar**
Signed-off-by: Lukas Bednar <lbednar@redhat.com>

### CODE REVIEW

**Comment by lukas-bednar** [comment]
there is some error 
```
+ echo 'Error: Failed to compile tests'
Error: Failed to compile tests
```
but it is not clear what is problem ... I was able to compile and run tests with this patch on my environment ...

**Comment by shiywang** [comment]
might looks like this one https://github.com/kubevirt/kubevirt-ansible/issues/382
cc @gbenhaim

**Comment by lukas-bednar** [comment]
@shiywang yes it is same thing ... do you know what might be problem ?

**Comment by shiywang** [comment]
ci test please

**Comment by lukas-bednar** [comment]
@shiywang thanks ;-)

**Pull request merged**
