### PR TITLE
Update cdi role with rbac for namespace

### PR DESCRIPTION
**Pull request by screeley44**
Found that cdi needed some extra permissions  @aglitke

### CODE REVIEW

**Comment by erinboyd** [comment]
lgtm

**Comment by erinboyd** [comment]
lgtm

**Comment by erinboyd** [comment]
/retest

tests appear to flake on ocp patch

**Comment by erinboyd** [comment]
@rthallisey  can you re-approve? Tests seem to be flaking

**Comment by lukas-bednar** [comment]
@gbenhaim it looks there is some problem with stdci, could you please take a look ?
```
 ERROR! Unexpected Exception, this is probably a bug: [Errno 28] No space left on device
```

**Comment by gbenhaim** [comment]
@lukas-bednar The Jenkins slave should be OK now.

**Comment by gbenhaim** [comment]
ci test please

**Comment by gbenhaim** [comment]
https://github.com/kubevirt/kubevirt-ansible/issues/150

**Comment by screeley44** [comment]
@gbenhaim - seems I'm still getting the no space on device unless there is something else failing that I'm not seeing?

```
[WARNING]: Could not match supplied host pattern, ignoring: all

 [WARNING]: provided hosts list is empty, only localhost is available

ERROR! Unexpected Exception, this is probably a bug: [Errno 28] No space left on device
```

**Comment by gbenhaim** [comment]
ci test please

**Comment by gbenhaim** [comment]
@screeley44 I'm checking

**Comment by screeley44** [comment]
ci test please

**Comment by gbenhaim** [comment]
@screeley44 looks like an issue with `docker-hub`
```
Unable to find image 'openshift/origin:v3.7' locally
Trying to pull repository docker.io/openshift/origin ... 
/usr/bin/docker-current: manifest for docker.io/openshift/origin:v3.7 not found.
```

**Comment by gbenhaim** [comment]
ci test please

**Comment by screeley44** [comment]
@gbenhaim thanks for the update!  I was green for like 2 hours I swear lol

**Comment by screeley44** [comment]
@gbenhaim @rthallisey - we are green!!!  can we get this merged?

**Pull request merged**
