### PR TITLE
cdi: Update the release to v0.5.0

### PR DESCRIPTION
**Pull request by aglitke**
CDI has produced a stable release (v0.5.0).  Adopt this release to
prevent unexpected changes to the CDI deployment.

Signed-off-by: Adam Litke <alitke@redhat.com>

### CODE REVIEW

**Comment by aglitke** [comment]
@rthallisey FYI

**Comment by shiywang** [comment]
still run into this error when I switch to v.0.5.0 stable version
```
[cnv-qe-jenkins@cnv-executor-shiywang kubevirt-ansible]$ oc get vms
NAME      AGE
test-vm   11m
[cnv-qe-jenkins@cnv-executor-shiywang kubevirt-ansible]$ oc get vms  test-vm -o jsonpath='{.status.phase}'
Failed[cnv-qe-jenkins@cnv-executor-shiywang kubevirt-ansible]$ oc describe vms 
Name:         test-vm
Namespace:    golden-images
Labels:       kubevirt.io/nodeName=cnv-executor-shiywang-node1.example.com
Annotations:  presets.virtualmachines.kubevirt.io/presets-applied=kubevirt.io/v1alpha1
API Version:  kubevirt.io/v1alpha1
Kind:         VirtualMachine
Metadata:
  Cluster Name:        
  Creation Timestamp:  2018-06-14T23:19:03Z
  Finalizers:
    foregroundDeleteVirtualMachine
  Generation:        1
  Resource Version:  155565
  Self Link:         /apis/kubevirt.io/v1alpha1/namespaces/golden-images/virtualmachines/test-vm
  UID:               53de7843-7029-11e8-97e1-fa163ecad8f5
Spec:
  Domain:
    Devices:
      Disks:
        Disk:
          Bus:        sata
        Name:         mydisk
        Volume Name:  pvcvolume
      Interfaces:
        Bridge:
        Name:  default
    Features:
      Acpi:
        Enabled:  true
    Firmware:
      Uuid:  b421f9ae-7257-4736-8c31-66406add8b0c
    Machine:
      Type:  q35
    Resources:
      Requests:
        Memory:  64M
  Networks:
    Name:  default
    Pod:
  Termination Grace Period Seconds:  0
  Volumes:
    Name:  pvcvolume
    Persistent Volume Claim:
      Claim Name:  golden-pvc
Status:
  Interfaces:
    Ip Address:  10.129.0.19
  Node Name:     cnv-executor-shiywang-node1.example.com
  Phase:         Failed
Events:
  Type     Reason              Age                 From                                                   Message
  ----     ------              ----                ----                                                   -------
  Normal   SuccessfulCreate    11m                 virtualmachine-controller                              Created virtual machine pod virt-launcher-test-vm-5slhz
  Normal   SuccessfulHandOver  10m                 virtualmachine-controller                              Pod owner ship transferred to the node virt-launcher-test-vm-5slhz
  Warning  SyncFailed          10m (x25 over 10m)  virt-handler, cnv-executor-shiywang-node1.example.com  server error. command Launcher.Sync failed: virError(Code=38, Domain=18, Message='Cannot access storage file '/var/run/kubevirt-private/vm-disks/pvcvolume/disk.img' (as uid:107, gid:107): No such file or directory')
  Warning  Stopped             2m                  virt-handler, cnv-executor-shiywang-node1.example.com  The VM crashed.
```

**Comment by jeffvance** [comment]
@shiywang Do you think the error above, _Cannot access storage file '/var/run/kubevirt-private/vm-disks/pvcvolume/disk.img' (as uid:107, gid:107): No such file or directory'_, is related to cdi? This pr is simply to inform consumers of the cdi images and/or manifests that cdi version v0.5.0 reverted the original pvc annotations.

**Comment by shiywang** [comment]
@jeffvance I don't know, this errors messages seems not that related. but the point is I think the environment I tested didn't change still the same slave and cluster I used yeterday, so as I tried last time, with yesterday's image and change to `cdi.io` annotations VM works well as I replied in email, so it's a little bit weird.

**Comment by shiywang** [comment]
@jeffvance after couple more try, it works, but I can guarantee I met this problem with exact same pvc and vm file, so it's not 100% reproducible bug I guess, but we I think we could merge this one first

**Comment by shiywang** [comment]
LGTM

**Comment by aglitke** [comment]
@rthallisey Can we merge this now?

**Pull request merged**
